package bwpt.tool.utils;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * CstCustomer generated by hbm2java
 */
public class CstCustomer implements java.io.Serializable {

	private Long custId;
	private String custName;
	private String custLinkman;
	private String custPhone;
	private String custMobile;
	private Date custCreatetime;
	//标识此属性不进行序列化
	@JSONField(serialize=false)
	private Set saleVisits = new HashSet(0);
	//标识此属性不进行序列化
	@JSONField(serialize=false)
	private Set cstLinkmans = new HashSet(0);

	public CstCustomer() {
	}

	public CstCustomer(String custName) {
		this.custName = custName;
	}


	public Long getCustId() {
		return this.custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}


	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCustLinkman() {
		return this.custLinkman;
	}

	public void setCustLinkman(String custLinkman) {
		this.custLinkman = custLinkman;
	}

	public String getCustPhone() {
		return this.custPhone;
	}

	public void setCustPhone(String custPhone) {
		this.custPhone = custPhone;
	}

	public String getCustMobile() {
		return this.custMobile;
	}

	public void setCustMobile(String custMobile) {
		this.custMobile = custMobile;
	}

	public Set getSaleVisits() {
		return this.saleVisits;
	}

	public void setSaleVisits(Set saleVisits) {
		this.saleVisits = saleVisits;
	}

	public Set getCstLinkmans() {
		return this.cstLinkmans;
	}

	public void setCstLinkmans(Set cstLinkmans) {
		this.cstLinkmans = cstLinkmans;
	}

	public Date getCustCreatetime() {
		return custCreatetime;
	}

	public void setCustCreatetime(Date custCreatetime) {
		this.custCreatetime = custCreatetime;
	}

}
